name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            homepath: $HOME
            homepath-quotes: '$HOME'

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world from ${{ runner.os }}!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${{ runner.os }}
        echo Home: ${{ matrix.homepath }}
        echo Home quoted: ${{ matrix.homepath-quotes }}
        
    - name: Run a shell script
      run: .github/workflows/runner-os.sh
